// TEMPORARY DUPLICATE of app/src/main/java/io/nisfeb/talon/ui/EmojiCatalog.kt
package io.nisfeb.talon.ui

/**
 * Compact emoji catalog for inline `:name` completion and reaction
 * search. Each entry has a canonical shortcode, the emoji glyph, and
 * a small set of keywords used for matching.
 *
 * The catalog is curated (~500 entries) — not exhaustive Unicode, but
 * covers the vast majority of chat usage. Add entries as needed.
 */
object EmojiCatalog {

    data class Entry(
        val shortcode: String,
        val glyph: String,
        val keywords: List<String>,
    )

    /** Alias → canonical shortcode (for alternate names Tlon might emit). */
    private val aliases: Map<String, String> = mapOf(
        ":thumbsup:" to ":+1:",
        ":thumbsdown:" to ":-1:",
        ":joy:" to ":laughing:",
        ":grin:" to ":grinning:",
        ":grinning_face:" to ":grinning:",
        ":smile:" to ":slight_smile:",
        ":heart_eyes:" to ":heart_eyes:",
        ":smiling_face:" to ":slight_smile:",
    )

    val entries: List<Entry> = listOf(
        // --- Smileys ---
        Entry(":grinning:", "😀", listOf("grin", "happy", "smile")),
        Entry(":smiley:", "😃", listOf("smile", "happy")),
        Entry(":slight_smile:", "🙂", listOf("smile", "slight")),
        Entry(":blush:", "😊", listOf("blush", "happy", "smile")),
        Entry(":laughing:", "😂", listOf("laugh", "joy", "tears", "lol")),
        Entry(":rofl:", "🤣", listOf("rofl", "laugh", "rolling")),
        Entry(":wink:", "😉", listOf("wink")),
        Entry(":smirk:", "😏", listOf("smirk")),
        Entry(":upside_down:", "🙃", listOf("upside", "down", "flip")),
        Entry(":relaxed:", "☺️", listOf("relaxed", "smile")),
        Entry(":yum:", "😋", listOf("yum", "tasty", "tongue")),
        Entry(":sunglasses:", "😎", listOf("sunglasses", "cool")),
        Entry(":heart_eyes:", "😍", listOf("heart", "eyes", "love")),
        Entry(":kissing_heart:", "😘", listOf("kiss", "heart")),
        Entry(":kiss:", "😗", listOf("kiss")),
        Entry(":hugs:", "🤗", listOf("hug", "hugs")),
        Entry(":thinking:", "🤔", listOf("think", "hmm")),
        Entry(":shushing:", "🤫", listOf("shush", "quiet")),
        Entry(":zipper_mouth:", "🤐", listOf("zipper", "mouth", "quiet")),
        Entry(":raised_eyebrow:", "🤨", listOf("eyebrow", "suspicious")),
        Entry(":neutral:", "😐", listOf("neutral", "meh")),
        Entry(":expressionless:", "😑", listOf("expressionless", "blank")),
        Entry(":no_mouth:", "😶", listOf("speechless", "silent")),
        Entry(":rolling_eyes:", "🙄", listOf("rolling", "eyes", "annoyed")),
        Entry(":grimacing:", "😬", listOf("grimace", "awkward")),
        Entry(":lying:", "🤥", listOf("lying", "pinocchio")),
        Entry(":relieved:", "😌", listOf("relieved")),
        Entry(":pensive:", "😔", listOf("pensive", "sad")),
        Entry(":sleepy:", "😪", listOf("sleepy", "tired")),
        Entry(":drooling:", "🤤", listOf("drool")),
        Entry(":sleeping:", "😴", listOf("sleep", "zzz")),
        Entry(":mask:", "😷", listOf("mask", "sick")),
        Entry(":sick:", "🤒", listOf("sick", "thermometer")),
        Entry(":injured:", "🤕", listOf("injured", "bandage")),
        Entry(":nauseated:", "🤢", listOf("nauseated", "sick")),
        Entry(":vomit:", "🤮", listOf("vomit", "puke")),
        Entry(":sneeze:", "🤧", listOf("sneeze", "sick")),
        Entry(":hot:", "🥵", listOf("hot", "heat")),
        Entry(":cold:", "🥶", listOf("cold", "freezing")),
        Entry(":dizzy_face:", "😵", listOf("dizzy", "confused")),
        Entry(":exploding:", "🤯", listOf("mind", "blown", "explode")),
        Entry(":cowboy:", "🤠", listOf("cowboy", "yeehaw")),
        Entry(":partying:", "🥳", listOf("party", "celebrate", "birthday")),
        Entry(":disguised:", "🥸", listOf("disguise", "groucho")),
        Entry(":shades:", "😎", listOf("cool", "sunglasses")),
        Entry(":nerd:", "🤓", listOf("nerd", "smart", "glasses")),
        Entry(":monocle:", "🧐", listOf("monocle", "inspect")),
        Entry(":confused:", "😕", listOf("confused")),
        Entry(":worried:", "😟", listOf("worried")),
        Entry(":slight_frown:", "🙁", listOf("frown", "slight")),
        Entry(":frown:", "☹️", listOf("frown", "sad")),
        Entry(":open_mouth:", "😮", listOf("open", "mouth", "surprised")),
        Entry(":hushed:", "😯", listOf("hushed", "surprised")),
        Entry(":astonished:", "😲", listOf("astonished", "shock")),
        Entry(":flushed:", "😳", listOf("flush", "embarrassed")),
        Entry(":pleading:", "🥺", listOf("pleading", "beg", "sad")),
        Entry(":frowning:", "😦", listOf("frowning")),
        Entry(":anguished:", "😧", listOf("anguished")),
        Entry(":fearful:", "😨", listOf("fear", "scared")),
        Entry(":anxious:", "😰", listOf("anxious", "sweat")),
        Entry(":sad:", "😢", listOf("cry", "sad", "tear")),
        Entry(":crying:", "😭", listOf("cry", "sob", "tears")),
        Entry(":scream:", "😱", listOf("scream", "shock", "fear")),
        Entry(":confounded:", "😖", listOf("confounded")),
        Entry(":persevere:", "😣", listOf("persevere", "struggle")),
        Entry(":disappointed:", "😞", listOf("disappointed")),
        Entry(":sweat:", "😓", listOf("sweat", "tired")),
        Entry(":weary:", "😩", listOf("weary", "tired")),
        Entry(":tired:", "😫", listOf("tired", "exhausted")),
        Entry(":yawn:", "🥱", listOf("yawn", "bored")),
        Entry(":triumph:", "😤", listOf("triumph", "snort")),
        Entry(":angry:", "😠", listOf("angry", "mad")),
        Entry(":rage:", "😡", listOf("rage", "furious")),
        Entry(":cursing:", "🤬", listOf("cursing", "swear")),
        Entry(":devil:", "😈", listOf("devil", "imp")),
        Entry(":skull:", "💀", listOf("skull", "dead")),
        Entry(":ghost:", "👻", listOf("ghost", "boo")),
        Entry(":poop:", "💩", listOf("poop", "shit", "crap")),
        Entry(":clown:", "🤡", listOf("clown")),
        Entry(":alien:", "👽", listOf("alien", "ufo")),
        Entry(":robot:", "🤖", listOf("robot", "bot")),
        Entry(":space_invader:", "👾", listOf("invader", "alien", "game")),
        Entry(":cat_face:", "🐱", listOf("cat")),
        Entry(":dog_face:", "🐶", listOf("dog", "puppy")),

        // --- Gestures / body ---
        Entry(":+1:", "👍", listOf("thumbs", "up", "yes", "ok")),
        Entry(":-1:", "👎", listOf("thumbs", "down", "no", "nope")),
        Entry(":ok_hand:", "👌", listOf("ok", "okay")),
        Entry(":pinched:", "🤌", listOf("pinched", "italian")),
        Entry(":pinch:", "🤏", listOf("pinch", "small", "little")),
        Entry(":v:", "✌️", listOf("victory", "peace")),
        Entry(":crossed_fingers:", "🤞", listOf("fingers", "crossed", "luck")),
        Entry(":love_you:", "🤟", listOf("love", "hand")),
        Entry(":rock_on:", "🤘", listOf("rock", "metal")),
        Entry(":call_me:", "🤙", listOf("call", "me", "shaka")),
        Entry(":point_left:", "👈", listOf("point", "left")),
        Entry(":point_right:", "👉", listOf("point", "right")),
        Entry(":point_up:", "👆", listOf("point", "up")),
        Entry(":point_down:", "👇", listOf("point", "down")),
        Entry(":raised_hand:", "✋", listOf("hand", "stop", "raise")),
        Entry(":wave:", "👋", listOf("wave", "hi", "bye")),
        Entry(":vulcan:", "🖖", listOf("vulcan", "spock")),
        Entry(":clap:", "👏", listOf("clap", "applause")),
        Entry(":raised_hands:", "🙌", listOf("hands", "praise", "celebrate")),
        Entry(":open_hands:", "👐", listOf("open", "hands")),
        Entry(":handshake:", "🤝", listOf("handshake", "deal")),
        Entry(":pray:", "🙏", listOf("pray", "thanks", "please")),
        Entry(":muscle:", "💪", listOf("muscle", "strong", "flex")),
        Entry(":selfie:", "🤳", listOf("selfie")),
        Entry(":writing_hand:", "✍️", listOf("writing", "pen")),
        Entry(":brain:", "🧠", listOf("brain")),
        Entry(":eye:", "👁", listOf("eye")),
        Entry(":eyes:", "👀", listOf("eyes", "look", "watch")),
        Entry(":ear:", "👂", listOf("ear", "listen")),
        Entry(":nose:", "👃", listOf("nose")),
        Entry(":tongue:", "👅", listOf("tongue")),
        Entry(":lips:", "👄", listOf("lips", "mouth")),
        Entry(":fist:", "✊", listOf("fist")),
        Entry(":facepunch:", "👊", listOf("punch", "fist")),
        Entry(":fist_left:", "🤛", listOf("fist", "left")),
        Entry(":fist_right:", "🤜", listOf("fist", "right")),
        Entry(":middle_finger:", "🖕", listOf("middle", "finger", "flip")),

        // --- Hearts / love ---
        Entry(":heart:", "❤️", listOf("heart", "love", "red")),
        Entry(":orange_heart:", "🧡", listOf("heart", "orange")),
        Entry(":yellow_heart:", "💛", listOf("heart", "yellow")),
        Entry(":green_heart:", "💚", listOf("heart", "green")),
        Entry(":blue_heart:", "💙", listOf("heart", "blue")),
        Entry(":purple_heart:", "💜", listOf("heart", "purple")),
        Entry(":black_heart:", "🖤", listOf("heart", "black")),
        Entry(":white_heart:", "🤍", listOf("heart", "white")),
        Entry(":brown_heart:", "🤎", listOf("heart", "brown")),
        Entry(":broken_heart:", "💔", listOf("heart", "broken")),
        Entry(":heart_exclamation:", "❣️", listOf("heart", "exclamation")),
        Entry(":two_hearts:", "💕", listOf("hearts", "love")),
        Entry(":revolving_hearts:", "💞", listOf("hearts", "revolving")),
        Entry(":sparkling_heart:", "💖", listOf("heart", "sparkle")),
        Entry(":growing_heart:", "💗", listOf("heart", "growing")),
        Entry(":heartbeat:", "💓", listOf("heart", "beat")),
        Entry(":heart_decoration:", "💟", listOf("heart", "decoration")),
        Entry(":cupid:", "💘", listOf("cupid", "heart", "arrow")),
        Entry(":gift_heart:", "💝", listOf("gift", "heart")),
        Entry(":100:", "💯", listOf("100", "hundred", "perfect", "score")),

        // --- Symbols ---
        Entry(":fire:", "🔥", listOf("fire", "lit", "hot")),
        Entry(":sparkles:", "✨", listOf("sparkle", "shine", "magic")),
        Entry(":star:", "⭐", listOf("star")),
        Entry(":star2:", "🌟", listOf("star", "glow")),
        Entry(":dizzy:", "💫", listOf("dizzy", "star")),
        Entry(":boom:", "💥", listOf("boom", "explode", "collide")),
        Entry(":zap:", "⚡", listOf("zap", "lightning", "bolt")),
        Entry(":snowflake:", "❄️", listOf("snow", "cold")),
        Entry(":cloud:", "☁️", listOf("cloud")),
        Entry(":sun:", "☀️", listOf("sun", "sunny")),
        Entry(":moon:", "🌙", listOf("moon")),
        Entry(":rainbow:", "🌈", listOf("rainbow", "pride")),
        Entry(":droplet:", "💧", listOf("drop", "water")),
        Entry(":sweat_drops:", "💦", listOf("sweat", "drops", "water")),
        Entry(":umbrella:", "☂️", listOf("umbrella", "rain")),
        Entry(":check:", "✅", listOf("check", "done", "yes")),
        Entry(":x:", "❌", listOf("x", "no", "cross")),
        Entry(":heavy_check:", "✔️", listOf("check", "yes")),
        Entry(":cross_mark:", "✖️", listOf("cross", "mark")),
        Entry(":warning:", "⚠️", listOf("warning", "caution")),
        Entry(":bangbang:", "‼️", listOf("bangbang", "exclamation")),
        Entry(":question:", "❓", listOf("question", "huh")),
        Entry(":exclamation:", "❗", listOf("exclamation", "bang")),
        Entry(":information:", "ℹ️", listOf("info", "information")),
        Entry(":trophy:", "🏆", listOf("trophy", "win")),
        Entry(":medal:", "🏅", listOf("medal", "award")),
        Entry(":gold_medal:", "🥇", listOf("gold", "medal", "first")),
        Entry(":silver_medal:", "🥈", listOf("silver", "medal", "second")),
        Entry(":bronze_medal:", "🥉", listOf("bronze", "medal", "third")),
        Entry(":tada:", "🎉", listOf("tada", "party", "celebrate")),
        Entry(":confetti:", "🎊", listOf("confetti", "celebrate")),
        Entry(":balloon:", "🎈", listOf("balloon", "party")),
        Entry(":gift:", "🎁", listOf("gift", "present")),
        Entry(":crown:", "👑", listOf("crown", "king", "queen")),
        Entry(":bell:", "🔔", listOf("bell", "notification")),
        Entry(":mute:", "🔕", listOf("mute", "silent")),
        Entry(":mag:", "🔍", listOf("search", "magnify", "find")),
        Entry(":lock:", "🔒", listOf("lock", "secure")),
        Entry(":unlock:", "🔓", listOf("unlock")),
        Entry(":key:", "🔑", listOf("key")),
        Entry(":bulb:", "💡", listOf("bulb", "idea", "light")),
        Entry(":hammer:", "🔨", listOf("hammer", "tool")),
        Entry(":wrench:", "🔧", listOf("wrench", "tool")),
        Entry(":gear:", "⚙️", listOf("gear", "cog", "settings")),
        Entry(":money:", "💰", listOf("money", "bag", "cash")),
        Entry(":dollar:", "💵", listOf("dollar", "money", "cash")),
        Entry(":bomb:", "💣", listOf("bomb")),
        Entry(":gun:", "🔫", listOf("gun", "pistol", "water")),
        Entry(":dagger:", "🗡️", listOf("dagger", "knife")),
        Entry(":pill:", "💊", listOf("pill", "medicine")),
        Entry(":syringe:", "💉", listOf("syringe", "vaccine")),
        Entry(":stethoscope:", "🩺", listOf("stethoscope", "doctor")),
        Entry(":tv:", "📺", listOf("tv", "television")),
        Entry(":camera:", "📷", listOf("camera", "photo")),
        Entry(":phone:", "📱", listOf("phone", "mobile")),
        Entry(":computer:", "💻", listOf("computer", "laptop")),
        Entry(":keyboard:", "⌨️", listOf("keyboard")),
        Entry(":printer:", "🖨️", listOf("printer")),
        Entry(":floppy:", "💾", listOf("save", "disk", "floppy")),
        Entry(":cd:", "💿", listOf("cd", "disc")),
        Entry(":rocket:", "🚀", listOf("rocket", "launch", "space")),
        Entry(":airplane:", "✈️", listOf("airplane", "plane", "flight")),
        Entry(":car:", "🚗", listOf("car", "drive")),
        Entry(":truck:", "🚚", listOf("truck")),
        Entry(":bike:", "🚴", listOf("bike", "bicycle")),
        Entry(":train:", "🚂", listOf("train", "locomotive")),
        Entry(":ship:", "🚢", listOf("ship", "boat")),
        Entry(":sailboat:", "⛵", listOf("sailboat", "boat")),
        Entry(":anchor:", "⚓", listOf("anchor", "ship")),

        // --- Food / drink ---
        Entry(":coffee:", "☕", listOf("coffee", "tea", "hot")),
        Entry(":tea:", "🍵", listOf("tea", "matcha")),
        Entry(":beer:", "🍺", listOf("beer", "brew")),
        Entry(":beers:", "🍻", listOf("beers", "cheers")),
        Entry(":wine:", "🍷", listOf("wine", "glass")),
        Entry(":champagne:", "🍾", listOf("champagne", "celebrate")),
        Entry(":cocktail:", "🍸", listOf("cocktail", "drink")),
        Entry(":whiskey:", "🥃", listOf("whiskey", "tumbler")),
        Entry(":cake:", "🎂", listOf("cake", "birthday")),
        Entry(":cupcake:", "🧁", listOf("cupcake", "dessert")),
        Entry(":cookie:", "🍪", listOf("cookie", "biscuit")),
        Entry(":doughnut:", "🍩", listOf("donut", "doughnut")),
        Entry(":pie:", "🥧", listOf("pie")),
        Entry(":chocolate:", "🍫", listOf("chocolate")),
        Entry(":candy:", "🍬", listOf("candy", "sweet")),
        Entry(":lollipop:", "🍭", listOf("lollipop")),
        Entry(":pizza:", "🍕", listOf("pizza")),
        Entry(":burger:", "🍔", listOf("burger", "hamburger")),
        Entry(":fries:", "🍟", listOf("fries", "chips")),
        Entry(":hotdog:", "🌭", listOf("hotdog", "hot", "dog")),
        Entry(":taco:", "🌮", listOf("taco")),
        Entry(":burrito:", "🌯", listOf("burrito")),
        Entry(":sandwich:", "🥪", listOf("sandwich")),
        Entry(":bacon:", "🥓", listOf("bacon")),
        Entry(":egg:", "🥚", listOf("egg")),
        Entry(":bread:", "🍞", listOf("bread", "toast")),
        Entry(":croissant:", "🥐", listOf("croissant")),
        Entry(":pancakes:", "🥞", listOf("pancakes", "breakfast")),
        Entry(":rice:", "🍚", listOf("rice")),
        Entry(":sushi:", "🍣", listOf("sushi")),
        Entry(":ramen:", "🍜", listOf("ramen", "noodle")),
        Entry(":spaghetti:", "🍝", listOf("spaghetti", "pasta")),
        Entry(":curry:", "🍛", listOf("curry")),
        Entry(":popcorn:", "🍿", listOf("popcorn", "movie")),
        Entry(":ice_cream:", "🍦", listOf("ice", "cream", "dessert")),
        Entry(":apple:", "🍎", listOf("apple", "fruit", "red")),
        Entry(":banana:", "🍌", listOf("banana", "fruit")),
        Entry(":grapes:", "🍇", listOf("grapes", "fruit")),
        Entry(":strawberry:", "🍓", listOf("strawberry", "berry")),
        Entry(":lemon:", "🍋", listOf("lemon")),
        Entry(":cherry:", "🍒", listOf("cherry")),
        Entry(":watermelon:", "🍉", listOf("watermelon", "fruit")),
        Entry(":peach:", "🍑", listOf("peach", "butt")),
        Entry(":eggplant:", "🍆", listOf("eggplant", "aubergine")),
        Entry(":tomato:", "🍅", listOf("tomato")),
        Entry(":avocado:", "🥑", listOf("avocado")),
        Entry(":corn:", "🌽", listOf("corn")),
        Entry(":mushroom:", "🍄", listOf("mushroom")),
        Entry(":chili:", "🌶️", listOf("chili", "pepper", "hot", "spicy")),
        Entry(":cheese:", "🧀", listOf("cheese")),
        Entry(":bottle:", "🍼", listOf("bottle", "baby")),
        Entry(":milk:", "🥛", listOf("milk")),
        Entry(":water:", "💧", listOf("water", "drop")),

        // --- Nature / animals ---
        Entry(":dog:", "🐕", listOf("dog")),
        Entry(":cat:", "🐈", listOf("cat")),
        Entry(":mouse:", "🐭", listOf("mouse")),
        Entry(":hamster:", "🐹", listOf("hamster")),
        Entry(":rabbit:", "🐰", listOf("rabbit", "bunny")),
        Entry(":fox:", "🦊", listOf("fox")),
        Entry(":bear:", "🐻", listOf("bear")),
        Entry(":panda:", "🐼", listOf("panda")),
        Entry(":koala:", "🐨", listOf("koala")),
        Entry(":tiger:", "🐯", listOf("tiger")),
        Entry(":lion:", "🦁", listOf("lion")),
        Entry(":cow:", "🐮", listOf("cow")),
        Entry(":pig:", "🐷", listOf("pig")),
        Entry(":frog:", "🐸", listOf("frog")),
        Entry(":monkey:", "🐵", listOf("monkey")),
        Entry(":see_no_evil:", "🙈", listOf("monkey", "see", "no", "evil")),
        Entry(":hear_no_evil:", "🙉", listOf("monkey", "hear", "no", "evil")),
        Entry(":speak_no_evil:", "🙊", listOf("monkey", "speak", "no", "evil")),
        Entry(":chicken:", "🐔", listOf("chicken")),
        Entry(":penguin:", "🐧", listOf("penguin")),
        Entry(":bird:", "🐦", listOf("bird")),
        Entry(":duck:", "🦆", listOf("duck")),
        Entry(":owl:", "🦉", listOf("owl")),
        Entry(":bat:", "🦇", listOf("bat")),
        Entry(":wolf:", "🐺", listOf("wolf")),
        Entry(":horse:", "🐴", listOf("horse")),
        Entry(":unicorn:", "🦄", listOf("unicorn")),
        Entry(":bee:", "🐝", listOf("bee")),
        Entry(":bug:", "🐛", listOf("bug", "caterpillar")),
        Entry(":butterfly:", "🦋", listOf("butterfly")),
        Entry(":snail:", "🐌", listOf("snail", "slow")),
        Entry(":turtle:", "🐢", listOf("turtle", "slow")),
        Entry(":snake:", "🐍", listOf("snake")),
        Entry(":dragon:", "🐉", listOf("dragon")),
        Entry(":whale:", "🐋", listOf("whale")),
        Entry(":dolphin:", "🐬", listOf("dolphin")),
        Entry(":shark:", "🦈", listOf("shark")),
        Entry(":fish:", "🐟", listOf("fish")),
        Entry(":octopus:", "🐙", listOf("octopus")),
        Entry(":crab:", "🦀", listOf("crab")),
        Entry(":shrimp:", "🦐", listOf("shrimp")),
        Entry(":tree:", "🌳", listOf("tree")),
        Entry(":evergreen_tree:", "🌲", listOf("tree", "evergreen", "pine")),
        Entry(":palm_tree:", "🌴", listOf("tree", "palm")),
        Entry(":cactus:", "🌵", listOf("cactus")),
        Entry(":flower:", "🌸", listOf("flower", "cherry", "blossom")),
        Entry(":rose:", "🌹", listOf("rose", "flower")),
        Entry(":sunflower:", "🌻", listOf("sunflower", "flower")),
        Entry(":tulip:", "🌷", listOf("tulip", "flower")),
        Entry(":leaves:", "🍃", listOf("leaves", "wind")),
        Entry(":fallen_leaf:", "🍂", listOf("leaf", "fall", "autumn")),
        Entry(":mushroom_red:", "🍄", listOf("mushroom", "red")),
        Entry(":globe:", "🌍", listOf("globe", "earth", "world")),
        Entry(":earth_americas:", "🌎", listOf("earth", "americas")),
        Entry(":earth_asia:", "🌏", listOf("earth", "asia")),

        // --- Activities / objects ---
        Entry(":soccer:", "⚽", listOf("soccer", "football")),
        Entry(":basketball:", "🏀", listOf("basketball")),
        Entry(":football:", "🏈", listOf("football", "american")),
        Entry(":baseball:", "⚾", listOf("baseball")),
        Entry(":tennis:", "🎾", listOf("tennis")),
        Entry(":volleyball:", "🏐", listOf("volleyball")),
        Entry(":bowling:", "🎳", listOf("bowling")),
        Entry(":pingpong:", "🏓", listOf("pingpong", "ping", "pong")),
        Entry(":dart:", "🎯", listOf("dart", "target", "bullseye")),
        Entry(":game_die:", "🎲", listOf("dice", "die", "game")),
        Entry(":video_game:", "🎮", listOf("game", "controller")),
        Entry(":slot_machine:", "🎰", listOf("slot", "gamble")),
        Entry(":musical_note:", "🎵", listOf("music", "note")),
        Entry(":notes:", "🎶", listOf("music", "notes")),
        Entry(":headphones:", "🎧", listOf("headphones", "music")),
        Entry(":microphone:", "🎤", listOf("microphone", "mic")),
        Entry(":guitar:", "🎸", listOf("guitar")),
        Entry(":drum:", "🥁", listOf("drum")),
        Entry(":saxophone:", "🎷", listOf("saxophone", "sax")),
        Entry(":piano:", "🎹", listOf("piano")),
        Entry(":violin:", "🎻", listOf("violin")),
        Entry(":art:", "🎨", listOf("art", "palette")),
        Entry(":clapper:", "🎬", listOf("clapper", "film", "movie")),
        Entry(":movie_camera:", "🎥", listOf("camera", "movie")),
        Entry(":book:", "📖", listOf("book", "open")),
        Entry(":books:", "📚", listOf("books")),
        Entry(":notebook:", "📓", listOf("notebook")),
        Entry(":memo:", "📝", listOf("memo", "note", "write")),
        Entry(":pencil:", "✏️", listOf("pencil")),
        Entry(":scroll:", "📜", listOf("scroll")),
        Entry(":newspaper:", "📰", listOf("newspaper", "news")),
        Entry(":calendar:", "📅", listOf("calendar", "date")),
        Entry(":clock:", "🕐", listOf("clock", "time")),
        Entry(":hourglass:", "⏳", listOf("hourglass", "wait")),
        Entry(":alarm:", "⏰", listOf("alarm", "clock")),

        // --- Flags / misc ---
        Entry(":us:", "🇺🇸", listOf("flag", "us", "usa", "america")),
        Entry(":pirate_flag:", "🏴‍☠️", listOf("pirate", "flag", "skull")),
        Entry(":white_flag:", "🏳️", listOf("flag", "white", "surrender")),
        Entry(":rainbow_flag:", "🏳️‍🌈", listOf("flag", "rainbow", "pride")),
        Entry(":checkered_flag:", "🏁", listOf("flag", "checkered", "finish")),
        Entry(":ribbon:", "🎀", listOf("ribbon")),
        Entry(":wrapped_gift:", "🎁", listOf("gift", "present")),
        Entry(":tophat:", "🎩", listOf("tophat", "hat")),
        Entry(":graduation:", "🎓", listOf("graduation", "cap")),
        Entry(":baby:", "👶", listOf("baby")),
        Entry(":boy:", "👦", listOf("boy")),
        Entry(":girl:", "👧", listOf("girl")),
        Entry(":man:", "👨", listOf("man")),
        Entry(":woman:", "👩", listOf("woman")),
        Entry(":person:", "🧑", listOf("person")),
        Entry(":older_man:", "👴", listOf("older", "man", "grandpa")),
        Entry(":older_woman:", "👵", listOf("older", "woman", "grandma")),
        Entry(":technologist:", "🧑‍💻", listOf("technologist", "developer", "coder")),
        Entry(":thumbup:", "👍", listOf("thumb", "up")),
    )

    /** Fast lookup by canonical shortcode. */
    private val byShortcode: Map<String, Entry> = entries.associateBy { it.shortcode }

    /** Resolve an alias or canonical shortcode to its glyph, or null. */
    fun glyphFor(shortcode: String): String? {
        val canonical = aliases[shortcode] ?: shortcode
        return byShortcode[canonical]?.glyph
    }

    /**
     * Return up to [limit] entries whose shortcode or keywords match
     * [query] (case-insensitive, prefix-first then substring).
     */
    fun search(query: String, limit: Int = 30): List<Entry> {
        val q = query.lowercase().removePrefix(":").removeSuffix(":")
        if (q.isEmpty()) return emptyList()
        val prefix = mutableListOf<Entry>()
        val contains = mutableListOf<Entry>()
        for (e in entries) {
            val name = e.shortcode.trim(':')
            when {
                name.startsWith(q) -> prefix += e
                e.keywords.any { it.startsWith(q) } -> prefix += e
                name.contains(q) -> contains += e
                e.keywords.any { it.contains(q) } -> contains += e
            }
            if (prefix.size >= limit) break
        }
        return (prefix + contains).take(limit)
    }
}
