package io.nisfeb.talon.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathNode
import androidx.compose.ui.graphics.vector.VectorGroup
import androidx.compose.ui.graphics.vector.VectorPath
import java.io.File
import kotlin.test.Test

/**
 * Writes TalonIcons.kt from [TalonIconSources]: the same path commands
 * the library holds, as source the app owns.
 *
 * Why: the extended icon library is 18 MB of Kotlin for the thousands
 * of icons it carries, and the iOS release link has to hold all of it
 * before dead-code elimination runs. Talon uses fifty. Owning those
 * fifty takes the library out of the link entirely.
 *
 * Run by hand, never by the suite:
 *   TALON_GENERATE_ICONS=1 ./gradlew :composeApp:desktopTest --tests '*GenerateTalonIcons*'
 * Then run TalonIconsFidelityTest, which proves the output equals the
 * originals, structurally, name included.
 */
class GenerateTalonIcons {

    @Test
    fun generate() {
        if (System.getenv("TALON_GENERATE_ICONS") != "1") return
        val out = File(System.getProperty("user.dir"), "src/commonMain/kotlin/io/nisfeb/talon/ui/icons/TalonIcons.kt")
        out.parentFile.mkdirs()
        out.writeText(render(TalonIconSources.all))
        println("wrote ${out.absolutePath}")
    }

    private fun render(icons: List<Pair<String, ImageVector>>): String = buildString {
        appendLine("// GENERATED by GenerateTalonIcons (desktopTest). Do not edit by hand;")
        appendLine("// rerun the generator after changing TalonIconSources.")
        appendLine("//")
        appendLine("// Path data copied from Google's Material Icons, Apache License 2.0.")
        appendLine("package io.nisfeb.talon.ui.icons")
        appendLine()
        appendLine("import androidx.compose.material.icons.materialIcon")
        appendLine("import androidx.compose.material.icons.materialPath")
        appendLine("import androidx.compose.ui.graphics.PathFillType")
        appendLine("import androidx.compose.ui.graphics.vector.ImageVector")
        appendLine()
        appendLine("/**")
        appendLine(" * The icons Talon needs from the extended Material set, owned here so")
        appendLine(" * the app links only the core set. Generated; see GenerateTalonIcons.")
        appendLine(" */")
        appendLine("object TalonIcons {")
        for ((name, vector) in icons) {
            appendLine()
            appendLine("    val $name: ImageVector by lazy {")
            append("        materialIcon(name = \"${vector.name}\"")
            if (vector.autoMirror) append(", autoMirror = true")
            appendLine(") {")
            for (node in vector.root) {
                val path = node as? VectorPath ?: error("$name: unexpected group in a material icon")
                val fill = path.fill
                check(fill is SolidColor && fill.value == Color.Black) { "$name: not a plain black fill" }
                // materialPath sets a stroke width of one with no stroke brush,
                // so the width says nothing; the brush is what would be drawn.
                check(path.stroke == null) { "$name: has a stroke" }
                val args = buildList {
                    if (path.fillAlpha != 1f) add("fillAlpha = ${lit(path.fillAlpha)}")
                    if (path.strokeAlpha != 1f) add("strokeAlpha = ${lit(path.strokeAlpha)}")
                    if (path.pathFillType == PathFillType.EvenOdd) add("pathFillType = PathFillType.EvenOdd")
                }
                appendLine("            materialPath(${args.joinToString(", ")}) {")
                for (n in path.pathData) appendLine("                ${call(n)}")
                appendLine("            }")
            }
            appendLine("        }")
            appendLine("    }")
        }
        appendLine()
        appendLine("    /** Every icon by name, for the fidelity test. */")
        appendLine("    fun entries(): List<Pair<String, ImageVector>> = listOf(")
        for ((name, _) in icons) appendLine("        \"$name\" to $name,")
        appendLine("    )")
        appendLine("}")
    }

    private fun lit(f: Float): String = "${f}f"

    private fun call(n: PathNode): String = when (n) {
        is PathNode.Close -> "close()"
        is PathNode.MoveTo -> "moveTo(${lit(n.x)}, ${lit(n.y)})"
        is PathNode.RelativeMoveTo -> "moveToRelative(${lit(n.dx)}, ${lit(n.dy)})"
        is PathNode.LineTo -> "lineTo(${lit(n.x)}, ${lit(n.y)})"
        is PathNode.RelativeLineTo -> "lineToRelative(${lit(n.dx)}, ${lit(n.dy)})"
        is PathNode.HorizontalTo -> "horizontalLineTo(${lit(n.x)})"
        is PathNode.RelativeHorizontalTo -> "horizontalLineToRelative(${lit(n.dx)})"
        is PathNode.VerticalTo -> "verticalLineTo(${lit(n.y)})"
        is PathNode.RelativeVerticalTo -> "verticalLineToRelative(${lit(n.dy)})"
        is PathNode.CurveTo -> "curveTo(${lit(n.x1)}, ${lit(n.y1)}, ${lit(n.x2)}, ${lit(n.y2)}, ${lit(n.x3)}, ${lit(n.y3)})"
        is PathNode.RelativeCurveTo -> "curveToRelative(${lit(n.dx1)}, ${lit(n.dy1)}, ${lit(n.dx2)}, ${lit(n.dy2)}, ${lit(n.dx3)}, ${lit(n.dy3)})"
        is PathNode.ReflectiveCurveTo -> "reflectiveCurveTo(${lit(n.x1)}, ${lit(n.y1)}, ${lit(n.x2)}, ${lit(n.y2)})"
        is PathNode.RelativeReflectiveCurveTo -> "reflectiveCurveToRelative(${lit(n.dx1)}, ${lit(n.dy1)}, ${lit(n.dx2)}, ${lit(n.dy2)})"
        is PathNode.QuadTo -> "quadTo(${lit(n.x1)}, ${lit(n.y1)}, ${lit(n.x2)}, ${lit(n.y2)})"
        is PathNode.RelativeQuadTo -> "quadToRelative(${lit(n.dx1)}, ${lit(n.dy1)}, ${lit(n.dx2)}, ${lit(n.dy2)})"
        is PathNode.ReflectiveQuadTo -> "reflectiveQuadTo(${lit(n.x)}, ${lit(n.y)})"
        is PathNode.RelativeReflectiveQuadTo -> "reflectiveQuadToRelative(${lit(n.dx)}, ${lit(n.dy)})"
        is PathNode.ArcTo -> "arcTo(${lit(n.horizontalEllipseRadius)}, ${lit(n.verticalEllipseRadius)}, ${lit(n.theta)}, ${n.isMoreThanHalf}, ${n.isPositiveArc}, ${lit(n.arcStartX)}, ${lit(n.arcStartY)})"
        is PathNode.RelativeArcTo -> "arcToRelative(${lit(n.horizontalEllipseRadius)}, ${lit(n.verticalEllipseRadius)}, ${lit(n.theta)}, ${n.isMoreThanHalf}, ${n.isPositiveArc}, ${lit(n.arcStartDx)}, ${lit(n.arcStartDy)})"
    }
}
